#!/bin/bash
set -e
DEPLOYMENT_ID="AKfycbyRkaDUTeGeJrd8vOYVfb5vvzn6MoPy6zFtDzLsk_2cwX_cQFPBPRq1gdBuTosR6H7m2Q"
DEPLOYMENT_URL="https://script.google.com/macros/s/${DEPLOYMENT_ID}/exec"
ACCESS_TOKEN=$(jq -r '.tokens.default.access_token' ~/.clasprc.json)

trap 'echo "❌ Push aborted due to failed clasp step."' ERR
echo "🔄 Pushing to Apps Script..."
clasp push
echo "🚀 Deploying web-api..."
clasp create-deployment -d "web-api" -i ${DEPLOYMENT_ID}
echo "🧪 Running tests..."
response=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -Ls "${DEPLOYMENT_URL}")
echo "$response"
if echo "$response" | grep -q "❌"; then
  exit 1
else
  exit 0
fi